---
abstract: 'Install non-code files for use during run-time'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-ShareFile
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Module::Install: 1.00
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Module-Install-ShareFile.git
version: 0.01
